// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7NFSNHCEjPoXom7muWWvtF-t9qx-UhE0',
    appId: '1:1087629899718:web:b34fb13edceab8b81c64c7',
    messagingSenderId: '1087629899718',
    projectId: 'talabat-7d3a0',
    authDomain: 'talabat-7d3a0.firebaseapp.com',
    storageBucket: 'talabat-7d3a0.firebasestorage.app',
    measurementId: 'G-3R65GZX4S9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfWW0jp9wt89OSs2d__9MoGiUGzNFCZ7U',
    appId: '1:1087629899718:android:a1a85a0df7268a671c64c7',
    messagingSenderId: '1087629899718',
    projectId: 'talabat-7d3a0',
    storageBucket: 'talabat-7d3a0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPH7eZ4QY0xdY3amSQ49yvedrrY7WUjec',
    appId: '1:1087629899718:ios:39dae27ec9b1dfe51c64c7',
    messagingSenderId: '1087629899718',
    projectId: 'talabat-7d3a0',
    storageBucket: 'talabat-7d3a0.firebasestorage.app',
    iosBundleId: 'com.example.talabat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPH7eZ4QY0xdY3amSQ49yvedrrY7WUjec',
    appId: '1:1087629899718:ios:39dae27ec9b1dfe51c64c7',
    messagingSenderId: '1087629899718',
    projectId: 'talabat-7d3a0',
    storageBucket: 'talabat-7d3a0.firebasestorage.app',
    iosBundleId: 'com.example.talabat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7NFSNHCEjPoXom7muWWvtF-t9qx-UhE0',
    appId: '1:1087629899718:web:5b3cf953d9d50f3c1c64c7',
    messagingSenderId: '1087629899718',
    projectId: 'talabat-7d3a0',
    authDomain: 'talabat-7d3a0.firebaseapp.com',
    storageBucket: 'talabat-7d3a0.firebasestorage.app',
    measurementId: 'G-1GFNPRV1KB',
  );
}
